### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by psteinroe** [supabase-community/postgres_lsp#136]
**[wip document]**

This tracks the current near-term plans for `postgres_lsp`.

**Groundwork**
- [ ] Stabilise change processing in base-db
- [ ] Rewrite statement splitter to be more resilient #135 
- [ ] Upstream pg_query extensions #132 
- [ ] Move lsp query logic from server into workspace crate for better separation of concerns and easier testing
- [ ] Expose lsp config 
- [ ] Setup release process 
- [ ] Setup clients for VSCode and Neovim LSP

**CLI**
- [ ] More versatile diagnostics crate (see biome as a reference implementation)
- [ ] CLI entry point

**Feature Work**
All of these are already there but need some love to be properly usable. 
- [ ] #134 which will make all of the below easier 
- [ ] #131 
- [ ] #130 
- [ ] #129 
- [x] #137

**Comment by psteinroe** [comment]
will post an update soon - we are very close to an "official" release though! please check the issues for open tasks. :)
